name: Test installation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  push:
    branches:
      - master
      - main
      - develop
      - "releases/**"

jobs:
  tests-linux:
    name: Test on Linux amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y curl git tar libc6-dev build-essential
      - name: Install Homebrew
        run: |
          mkdir -p ~/.linuxbrew
          curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip-components 1 -C ~/.linuxbrew
          ~/.linuxbrew/bin/brew shellenv >> $GITHUB_ENV
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install katenary formula
        run: |
          eval "$(~/.linuxbrew/bin/brew shellenv)"
          brew install ./Formula/katenary.rb
      - name: Test katenary binary
        run: ~/.linuxbrew/bin/katenary --version && echo "Linux test OK"

  tests-macos:
    name: Test on macOS arm64
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew update
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install katenary formula
        run: brew install $(pwd)/Formula/katenary.rb
      - name: Check installed binary
        run: |
          uname -a
          ls -l $(which katenary)
          file -s $(which katenary)
      - name: Test katenary binary
        run: katenary --version && echo "macOS test OK"
